/* automatically generated by rust-bindgen 0.57.0 */

extern "C" {
    pub fn likwid_markerInit();
}
extern "C" {
    pub fn likwid_markerThreadInit();
}
extern "C" {
    pub fn likwid_markerNextGroup();
}
extern "C" {
    pub fn likwid_markerClose();
}
extern "C" {
    pub fn likwid_markerRegisterRegion(
        regionTag: *const ::std::os::raw::c_char,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn likwid_markerStartRegion(
        regionTag: *const ::std::os::raw::c_char,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn likwid_markerStopRegion(
        regionTag: *const ::std::os::raw::c_char,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn likwid_markerResetRegion(
        regionTag: *const ::std::os::raw::c_char,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn likwid_markerGetRegion(
        regionTag: *const ::std::os::raw::c_char,
        nr_events: *mut ::std::os::raw::c_int,
        events: *mut f64,
        time: *mut f64,
        count: *mut ::std::os::raw::c_int,
    );
}
